### ISSUE TITLE
Model tests stopped working on machines without a GPU

### ISSUE THREAD

**Issue by piotrekobi** [PaddlePaddle/PaddleTest#1786]
After 97a182aaa6e880e76216cbb6e74a2ccde90afd95 the tests from this repository stopped working on our validation machines. This is because 97a182aaa6e880e76216cbb6e74a2ccde90afd95 enables monitor.py, which requires the nvidia-smi, which our validation machines don't have.
Humansegv2 and ppyoloe are high priority models that we were told to optimize by @yaomichael, but we can't do this if this repository keeps adding changes that make it impossible to run the models on machines without a GPU. Most of our machines don't have GPU's, because OneDNN only runs on CPU.
Please decide if we should keep trying to optimize the oneDNN versions of these models and if so, please make it possible to run the tests of these models on machines without a GPU.

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/PaddleTest/pull/1768

**Comment by piotrekobi** [comment]
This is the PR that caused the issue

**Comment by yaomichael** [comment]
https://github.com/PaddlePaddle/PaddleTest/pull/1809 fixed this issue

**Comment by piotrekobi** [comment]
https://github.com/PaddlePaddle/PaddleTest/pull/1809 Fixed the issue for the humanseg models, but we also test the ppyoloe and picodet models in our validation.  We are still getting a nvidia-smi not found error when we run them. @zhoutianzi666 could you please add a similar fix to test_int8_model/test_ppyoloe_infer.py? That way these models should start working for us again.

**Comment by yaomichael** [comment]
@piotrekobi https://github.com/PaddlePaddle/PaddleTest/pull/1851 should have fixed this problem, can you check again?
