### ISSUE TITLE
测试框架中动态图和静态图在相同随机种子下产出的结果不一致问题

### ISSUE THREAD

**Issue by iverxin** [PaddlePaddle/PaddleTest#240]
framework.api.nn.apibase 的run和_baserun函数中，在动态图和静态图之间没有重置self.seed，会导致在测试含有随机过程的组件，如dropout，随机产生的掩码不一致，导致动态图和静态图的输出结果不一样。致使测试失败。
需要在中间重新重置随机种子。

**Comment by DDDivano** [comment]
静态图的种子设定写在这里了。
这个原因是因为在之前版本，是没有paddle.seed()这个函数的，静态图的设置需要直接指定program.seed来设置，后续升级就保留了一个该用法用来检测兼容性。
![image](https://user-images.githubusercontent.com/10734244/137086799-ae13dc73-2339-4e39-be3c-3d16ff06de6c.png)

**Comment by iverxin** [comment]
嗯哪，但是在else if条件里面没有重置随机种子，不确定这个是有意为之还是忘记了。。
![image](https://user-images.githubusercontent.com/32192043/137102218-25829fd7-2961-465c-9af9-8358856c99f8.png)

**Comment by DDDivano** [comment]
> 嗯哪，但是在else if条件里面没有重置随机种子，不确定这个是有意为之还是忘记了。。 ![image](https://user-images.githubusercontent.com/32192043/137102218-25829fd7-2961-465c-9af9-8358856c99f8.png)

![image](https://user-images.githubusercontent.com/10734244/137452243-964b2119-12cb-4cc6-a2c4-096df6de8408.png)
这个就是 paddle.seed 底层写法，之前没有这个函数的时候，就是这么使用的，这个没有修改主要是为了对过去版本的兼容

**Comment by iverxin** [comment]
明白了  Thanks
