### ISSUE TITLE
test_fast_rcnn_trt_fp32.py 中使用conditional_block_infer 

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleTest#2770]
https://github.com/PaddlePaddle/Paddle/pull/63507

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/10494744/stage/16301033/0?jump=latestJob

test_fast_rcnn_trt_fp32.py 中使用conditional_block_infer 即将移除，PaddleTest中有使用，麻烦看下是否能修改
![image](https://github.com/PaddlePaddle/PaddleTest/assets/4617245/5bf2713e-fdbf-4391-ae98-50a5bf90346a)

@EmmonsCurse

**Comment by EmmonsCurse** [comment]
@co63oc ok，我这边做一下适配验证
